library(gdata)
library(ggplot2)
library(reshape)
require(gridExtra)

# the simulation data was generated by the Vensim model

pop <- read.xls("models/04 chapter/R/Data Population.xlsx",stringsAsFactors=FALSE)
names(pop)[which(names(pop)=="Population.Aged.0.14")]<-"0-14"
names(pop)[which(names(pop)=="Population.Aged.15.39")]<-"15-39"
names(pop)[which(names(pop)=="Population.Aged.40.64")]<-"40-64"
names(pop)[which(names(pop)=="Population.Aged.65.")]<-"65+"
names(pop)[which(names(pop)=="General.Practitioners")]<-"GPs"
names(pop)[which(names(pop)=="Desired.GPs")]<-"TargetGPs"


melt_pop<-melt(pop,id.vars="Time",
               measure.vars=c("0-14","15-39","40-64","65+"))
names(melt_pop) = c("Time","Cohort","Size")

p1<-ggplot(melt_pop,aes(x=Time,y=Size,fill=Cohort)) + geom_area() + 
  xlab("Year") +
  ylab("Persons")  +
  guides(fill=guide_legend(title=NULL))+
  scale_y_continuous(labels = comma)+
  #annotate("text", x = 2016, y = 2000000, label = "Text 1")
  ggtitle("")+
  theme(legend.position="none")

p2<-ggplot()+
  geom_line(data=pop,aes(Time,TargetGPs,color="GPs Target"),linetype="dashed")+
  geom_line(data=pop,aes(Time,GPs,color="GPs"))+
  ylab("GPs (Target and Actual)")+
  theme(legend.position="none")

g1<-grid.arrange(p1, p2, nrow=1, ncol=2)


cap <- read.xls("models/04 chapter/R/Capacity.xlsx")

attach(cap)
p3<-ggplot()+
  geom_line(data=cap,linetype="dashed",aes(Time,NP.Desired.Completed.Visits,color="DCV(1)"))+
  geom_line(data=cap,aes(Time,NP.Potential.Completed.Visits,color="PCV(1)"))+
  geom_line(data=cap,linetype="dashed",aes(Time,POL.Desired.Completed.Visits,color="DCV(2)"))+ 
  geom_line(data=cap,aes(Time,POL.Potential.Completed.Visits,color="PCV(2)"))+  
  ylab("Patient Visits Per Year")+
  guides(fill=guide_legend(title=NULL))+
  scale_y_continuous(labels = comma)+
  labs(color="")+
  theme(legend.position="bottom")


p4<-ggplot()+
  geom_line(data=cap,aes(Time,Effect.of.System.Pressure.on.Productivity,color="ESP-P(2)"))+
  geom_line(data=cap,aes(Time,Effect.of.System.Pressure.on.Work.Year,color="ESP-WY(2)"))+
  ylab("Effects of System Pressure on Capacity")+
  guides(fill=guide_legend(title=NULL))+
  scale_y_continuous(labels = comma)+
  labs(color="")+
  theme(legend.position="bottom")

g2<-grid.arrange(p3, p4, nrow=1, ncol=2)

